### ISSUE TITLE
Bugs in the OAuth 2.0 Resource Set Registration Spec example

### ISSUE THREAD

**Issue by mefarazath** [xmlgrrl/UMA-Specifications#173] opened 2015-07-16 01:19 UTC
I am referring to the example[1] in the spec,

*The example used HTTP PUT method to create a new Resource Set instead of using HTTP POST method as explained in the spec.

*The example responds to an Update of a Resource Set with "HTTP/1.1 201 Created" instead of a "HTTP/1.1 204 No Content" response as mentioned in the spec

[1] https://docs.kantarainitiative.org/uma/draft-oauth-resource-reg.html#resource-reg-example

**Comment by mmachulak** [comment] 2015-07-20 21:13
Part 1

"*The example used HTTP PUT method to create a new Resource Set instead of using HTTP POST method as explained in the spec."

is a duplicate of: https://github.com/xmlgrrl/UMA-Specifications/issues/148

**Comment by xmlgrrl** [comment] 2015-07-30 16:32
We'll close now.

**Closed by xmlgrrl** 2015-07-30 16:32 UTC
Labels: rsrc-reg
